#!/usr/bin/env python3
"""Generate the journal-submission variant of Paper 2.

    python3 the_third_turn/paper/make_journal_variant.py

WHAT THIS TESTS. The working-paper edition opens with a large Status-and-scope box
before the abstract. It is the right choice for a preprint a reader meets cold. For a
journal submission it pushes the abstract down the first page, and some editors read a
front-matter caveat box as hedging rather than as disclosure.

This variant relocates that box **verbatim** to the head of Section 6.6 -- the section
that defines the four conditions the box describes -- so the first page carries title and
abstract.

WHAT IS NOT WEAKENED. Nothing in the box is cut, softened, or reworded; it moves whole.
Disclosure on the first page is preserved by three things that remain:

  1. the title block still reads "Gate applied: Outcome C - non-identification";
  2. the abstract already states that the quantity is not identifiable without richer
     instrumentation;
  3. a one-line pointer after the abstract names the pre-registration, the gate, the
     post-evidence amendment and its tripwire, and sends the reader to Section 6.6.

If a reader of this variant can reach any wrong impression the working-paper edition would
have prevented, the relocation has failed and should be reverted. Reverting is a one-line
change: drop this script from the build.
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC, OUT = HERE / "paper2.md", HERE / "paper2_journal.md"
SECTION_66 = "### 6.6 Conditions required before results may be reported\n"

POINTER = (
    "*This paper is pre-registered. Section 6.5 fixes the analysis plan and Section 6.6 the four\n"
    "conditions that gate what may be reported, together with the determination those conditions\n"
    "returned, a dated post-evidence amendment, and the tripwire that binds the unsatisfied\n"
    "conditions again the moment any estimate is attempted. The full statement appears at the head\n"
    "of Section 6.6.*\n"
)


def main() -> int:
    text = SRC.read_text()

    # Lift the box: the contiguous run of blockquote lines before the abstract.
    lines = text.splitlines(keepends=True)
    start = next((i for i, l in enumerate(lines) if l.startswith("> **Status and scope.**")), None)
    if start is None:
        sys.exit("make_journal_variant: status box not found in paper2.md")
    end = start
    while end < len(lines) and lines[end].startswith(">"):
        end += 1
    box = "".join(lines[start:end]).rstrip("\n") + "\n"
    rest = "".join(lines[:start]) + "".join(lines[end:])
    rest = rest.replace("\n\n\n", "\n\n")

    # Front-page pointer: immediately before the first section heading after the abstract.
    anchor = "\n## 1. Introduction\n"
    if anchor not in rest:
        sys.exit("make_journal_variant: introduction heading not found")
    rest = rest.replace(anchor, "\n" + POINTER + anchor, 1)

    # Reseat the box, verbatim, at the head of the section it describes.
    if SECTION_66 not in rest:
        sys.exit("make_journal_variant: section 6.6 heading not found")
    rest = rest.replace(SECTION_66, SECTION_66 + "\n" + box, 1)

    banner = ("<!-- JOURNAL SUBMISSION VARIANT. Generated by paper/make_journal_variant.py from "
              "paper2.md; do not edit by hand. The manuscript of record is paper2.md. The "
              "Status-and-scope box is relocated verbatim to Section 6.6; nothing is cut. -->\n")
    OUT.write_text(banner + rest)

    # Verify the disclosure survived intact.
    produced = OUT.read_text()
    checks = {
        "box present, verbatim": box.strip() in produced,
        "box moved out of front matter": produced.index(box.strip()) > produced.index("## Abstract"),
        "pointer present": "This paper is pre-registered." in produced,
        "Outcome C on title block": "Gate applied: Outcome C" in produced,
        "tripwire named": "tripwire" in produced,
        "GD-21 amendment named": "amendment" in produced,
        "no estimate claim intact": "No\n> numerical estimate of the pricing contrast is reported anywhere in this paper" in produced,
    }
    for k, v in checks.items():
        print(f"  [{'OK' if v else 'FAIL'}] {k}")
    return 0 if all(checks.values()) else 1


if __name__ == "__main__":
    raise SystemExit(main())
