#!/usr/bin/env python3
"""Generate the paper's figure set (Fig 2–7) from committed result JSONs.

Figure 1 is the Mermaid research-process flow (in the outline). This script
produces the six data figures as PNGs in paper/figures/. Every number is read
from output/*.json (recomputable from the committed caches — no feed fetches).

    python the_third_turn/paper/make_figures.py

Figures are generated by filename; the manuscript figure NUMBERS are assigned by
order of appearance in paper1.md (which also includes the two conceptual figures
from make_concept_figures.py), so the numbering lives in the paper, not here.

Reviewer constraints honored throughout: uncertainty is shown (bootstrap /
Hanley-McNeil / Wilson CIs), near-zero differences are drawn NEUTRAL (the CI
does the arguing, not the color), typography is one coherent system (figstyle),
labels crossing gridlines wear a white halo, and the result is framed as a
BOUNDARY we identify — never a "negative result."
"""

from __future__ import annotations

import json
import json
import math
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from matplotlib.patches import Patch, FancyBboxPatch, FancyArrowPatch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import figstyle as fs  # noqa: E402

OUT = HERE.parent / "output"
FIGDIR = HERE / "figures"
FIGDIR.mkdir(exist_ok=True)

# white halo so a label crossing a gridline / mark stays legible
HALO = dict(facecolor="white", edgecolor="none", alpha=0.78, boxstyle="round,pad=0.15")


def _load(name):
    return json.loads((OUT / name).read_text())


def _wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (c - h, c + h)


def _hanley_mcneil_ci(a, n, prev, z=1.96):
    """Analytic 95% CI for an AUC (Hanley & McNeil 1982)."""
    n1 = max(int(round(prev * n)), 1)          # positives
    n2 = max(n - n1, 1)                          # negatives
    q1 = a / (2 - a)
    q2 = 2 * a * a / (1 + a)
    var = (a * (1 - a) + (n1 - 1) * (q1 - a * a) + (n2 - 1) * (q2 - a * a)) / (n1 * n2)
    se = math.sqrt(max(var, 0.0))
    return se, (max(a - z * se, 0.0), min(a + z * se, 1.0))


# ─────────────────────────────────────────────────────────────────────────────
# Figure 2 — the hypothesis graveyard
# ─────────────────────────────────────────────────────────────────────────────
def fig2_graveyard():
    stages = ["Initial\nsignal", "Robustness", "Out-of-\nsample", "Market\ntest", "Verdict"]
    P, F, N = "P", "F", "N"
    # each row: how far the hypothesis cleared before a gate killed it (Verdict always F)
    rows = [
        ("Times-through-order (TTOP)",      [P, F, N, N, F]),
        ("Velocity decline",               [P, F, N, N, F]),
        ("Bullpen-fatigue multiplier",     [F, N, N, N, F]),
        ("Drop reversion (Over)",          [P, P, F, N, F]),
        ("Drop reversion (Under)",         [P, F, N, N, F]),
        ("Alternate-line skew",            [P, P, P, F, F]),
        ("Early-run anchoring",            [P, P, P, F, F]),
        ("Weather / park context",         [P, P, P, F, F]),
        ("Remaining-runs fatigue term",    [P, F, N, N, F]),
        ("Forecast encompassing",          [P, P, F, F, F]),
    ]
    color = {P: fs.PASS, F: fs.FAIL, N: fs.GRID}
    glyph = {P: "✓", F: "✗", N: "·"}  # ✓ ✗ ·
    txtcol = {P: "white", F: "white", N: fs.MUTED}

    fs.setup()
    fig, ax = plt.subplots(figsize=(fs.FULL_W, 4.4))
    nrows, ncols = len(rows), len(stages)
    for i, (_, cells) in enumerate(rows):
        y = nrows - 1 - i
        for j, c in enumerate(cells):
            ax.add_patch(plt.Rectangle((j + 0.06, y + 0.06), 0.88, 0.88,
                                       facecolor=color[c], edgecolor="white", linewidth=1.5))
            ax.text(j + 0.5, y + 0.5, glyph[c], ha="center", va="center",
                    color=txtcol[c], fontsize=13, fontweight="bold")
    ax.set_xlim(0, ncols)
    ax.set_ylim(0, nrows)
    ax.set_xticks([j + 0.5 for j in range(ncols)])
    ax.set_xticklabels(stages, fontsize=9)
    ax.set_yticks([nrows - 1 - i + 0.5 for i in range(nrows)])
    ax.set_yticklabels([r[0] for r in rows], fontsize=9)
    ax.xaxis.tick_top()
    ax.tick_params(length=0)
    for s in ax.spines.values():
        s.set_visible(False)
    ax.grid(False)
    ax.set_title("Each public-information candidate, tested against the market forecast",
                 pad=26, fontsize=12, wrap=True)
    legend = [Patch(facecolor=fs.PASS, label="cleared this test"),
              Patch(facecolor=fs.FAIL, label="failed here"),
              Patch(facecolor=fs.GRID, label="not reached")]
    ax.legend(handles=legend, loc="upper center", bbox_to_anchor=(0.5, -0.04),
              ncol=3, fontsize=9, handlelength=1.1)
    fs.save_at_measure(fig, FIGDIR / "hypothesis_elimination.png")
    plt.close(fig)
    return rows


# ─────────────────────────────────────────────────────────────────────────────
# Figure 3 — forecast encompassing
# ─────────────────────────────────────────────────────────────────────────────
def fig3_encompassing():
    e = _load("encompass.json")
    fs.setup()
    # Left/right is fixed by the caption, so the panels stay side by side and the
    # left one is given room instead: a wider share, taller canvas for the
    # title/annotation stack, and category labels broken onto short lines. At
    # [1, 1.25] the left panel was ~2.7in and "Market + features" alone needed
    # ~1.06in against 0.9in of slot.
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(fs.FULL_W, 4.5),
                                   gridspec_kw={"width_ratios": [1, 1.12]})
    # Panel spacing is the layout engine's: constrained_layout ignores
    # subplots_adjust and warns, and the width_ratios above already give the
    # left panel the room its three-line tick labels need.

    # left — three forecasts
    labels = ["Our\nfeatures\n(Y ~ X)", "Sharp\nmarket\n(Y ~ B)", "Market\n+ features\n(Y ~ B+X)"]
    vals = [e["r2_features"], e["r2_market"], e["r2_both"]]
    cols = [fs.PALETTE[1], fs.PALETTE[0], fs.PALETTE[2]]
    x = np.arange(3)
    axL.bar(x, vals, width=0.62, color=cols, zorder=3)
    for xi, v in zip(x, vals):
        axL.text(xi, v + 0.006, f"{v:.3f}", ha="center", va="bottom",
                 fontsize=10, fontweight="bold", color=fs.INK)
    # visual annotation over the combined bar — tells the reader what they're seeing
    axL.annotate("no incremental\ninformation", xy=(2, vals[2] + 0.004),
                 xytext=(2, vals[2] + 0.070), ha="center", va="bottom", fontsize=8.6,
                 color=fs.PALETTE[3], fontweight="bold",
                 arrowprops=dict(arrowstyle="-", color=fs.PALETTE[3], linewidth=1))
    axL.set_xticks(x)
    axL.set_xticklabels(labels, fontsize=9)
    axL.set_ylabel("out-of-sample R²  (remaining runs)")
    axL.set_ylim(0, max(vals) * 1.34)   # clear space for the annotation
    # Both panel titles are set to two lines so their baselines align.
    axL.set_title("Adding features to the market:\nΔR² = %+.3f" % e["encompass_gain"],
                  fontsize=11, pad=10)

    # right — per-feature incremental ΔR² beyond the market (E+)
    inc = e["incremental"]
    order = sorted(inc.items(), key=lambda kv: kv[1])
    names = [k for k, _ in order]
    dvals = [v for _, v in order]
    y = np.arange(len(names))
    bar_cols = [fs.NEUTRAL if abs(v) < 0.003 else (fs.PALETTE[2] if v > 0 else fs.PALETTE[3])
                for v in dvals]
    bar_hatch = [fs.HATCH if abs(v) < 0.003 else "" for v in dvals]
    bars = axR.barh(y, dvals, color=bar_cols, zorder=3, height=0.66,
                    edgecolor=fs.MUTED, linewidth=0.0)
    for b, hh in zip(bars, bar_hatch):          # texture only on the neutral band
        if hh:
            b.set_hatch(hh); b.set_edgecolor(fs.MUTED); b.set_linewidth(0.6)
    axR.axvline(0, color=fs.MUTED, linewidth=1)
    axR.axvline(0.003, color=fs.GRID, linewidth=1, linestyle="--")
    axR.axvline(-0.003, color=fs.GRID, linewidth=1, linestyle="--")
    axR.set_yticks(y)
    axR.set_yticklabels(names, fontsize=9)
    axR.set_xlabel("incremental R² beyond the market  (Y~B+Xi − Y~B)")
    axR.set_title("Every feature,\nindividually encompassed", fontsize=11, pad=10)
    # Mid-height, hard right. The bars are sorted by value, so the middle rows are
    # the ones inside the negligible band and their bars are the shortest -- the only
    # part of the panel guaranteed clear. (The bottom-right corner is not: bars grow
    # from zero, so the longest negative bar reaches the zero rule at the bottom row
    # and the label overprinted its tip.)
    axR.text(0.985, 0.52, "±0.003\nnegligible band", transform=axR.transAxes,
             fontsize=8.5, color=fs.MUTED, va="center", ha="right")
    fig.suptitle("The sharp market statistically encompasses every public variable we measure",
                 fontsize=12.5, fontweight="bold", wrap=True)
    fs.save_at_measure(fig, FIGDIR / "forecast_encompassing.png")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 4 — velocity debiasing
# ─────────────────────────────────────────────────────────────────────────────
def fig4_debiasing():
    # recomputed from calibration.py (committed run): AUC / n / class prevalence
    prev = _load("calibration.json").get("base_rate", 0.429)
    bars = [
        ("BASELINE\ntier only, no velocity", 0.420, 272, fs.NEUTRAL),
        ("POST-TREATMENT\nvel drop 1st→3rd time", 0.610, 272, fs.PALETTE[3]),
        ("DEBIASED\nearly-window decline", 0.524, 319, fs.PALETTE[0]),
    ]
    fs.setup()
    # Stacked, not side by side. At half the text measure each panel was ~3.4in
    # wide: the flow diagram's boxes clipped their own labels and the bar chart's
    # three category labels overprinted one another. Each panel now gets the full
    # measure, which is what both of them needed.
    fig, (axL, axR) = plt.subplots(2, 1, figsize=(fs.FULL_W, 7.4),
                                   gridspec_kw={"height_ratios": [1.0, 0.95]})
    # Row spacing likewise belongs to constrained_layout.

    # ---- LEFT: the survivorship flow (why the raw signal is post-treatment) ----
    axL.set_xlim(0, 10); axL.set_ylim(0, 10); axL.axis("off")

    def _fbox(x, y, w, h, fc, ec=None, lw=1.4):
        axL.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.02,rounding_size=0.12",
                                     facecolor=fc, edgecolor=ec or "white", linewidth=lw, zorder=3))

    def _farrow(x0, y0, x1, y1, color=None, lw=1.9):
        axL.add_patch(FancyArrowPatch((x0, y0), (x1, y1), arrowstyle="-|>", mutation_scale=13,
                                      color=color or fs.MUTED, linewidth=lw, zorder=2,
                                      shrinkA=0, shrinkB=0))

    _fbox(1.7, 8.35, 6.6, 1.25, fs.PALETTE[0])
    axL.text(5.0, 8.97, "100 starters take the mound", ha="center", va="center",
             color="white", fontsize=9.8, fontweight="bold")
    _farrow(4.1, 8.35, 2.4, 6.95)
    _farrow(5.9, 8.35, 7.6, 6.95, color=fs.PASS)
    _fbox(0.25, 5.5, 3.9, 1.45, "#ECECEC", ec=fs.GRID)
    axL.text(2.2, 6.42, "pulled or shelled early", ha="center", va="center", color=fs.MUTED,
             fontsize=8.5, fontweight="bold")
    axL.text(2.2, 6.02, "(before the 3rd time through)", ha="center", va="center",
             color=fs.MUTED, fontsize=8.5)
    axL.text(2.2, 5.05, "✗ leaves the sample", ha="center", va="center", color=fs.FAIL,
             fontsize=8.5, fontweight="bold")
    _fbox(5.75, 5.5, 4.0, 1.45, fs.PASS)
    axL.text(7.75, 6.42, "survive to face the", ha="center", va="center", color="white",
             fontsize=8.7, fontweight="bold")
    axL.text(7.75, 6.02, "order a 3rd time", ha="center", va="center", color="white",
             fontsize=8.7, fontweight="bold")
    _farrow(7.75, 5.5, 5.85, 3.8)
    _fbox(1.5, 2.2, 8.3, 1.5, fs.INK)
    axL.text(5.65, 3.17, "velocity decline measured HERE", ha="center", va="center",
             color="white", fontsize=9.0, fontweight="bold")
    axL.text(5.65, 2.68, "only on survivors, pitchers already good enough to last",
             ha="center", va="center", color="white", fontsize=8.5)
    axL.text(5.0, 1.15, "the sample is conditioned on survival,\nso the raw signal is post-treatment",
             ha="center", va="center", color=fs.MUTED, fontsize=8.5, style="italic")
    axL.set_title("A signal defined only on the survivors", fontsize=10.6, pad=8, wrap=True)

    # ---- RIGHT: the AUC drop under debiasing ----
    x = np.arange(len(bars))
    for xi, (lab, a, n, c) in zip(x, bars):
        se, (lo, hi) = _hanley_mcneil_ci(a, n, prev)
        axR.bar(xi, a, width=0.6, color=c, zorder=3)
        axR.errorbar(xi, a, yerr=[[a - lo], [hi - a]], fmt="none",
                     ecolor=fs.INK, elinewidth=1.4, capsize=5, zorder=4)
        axR.text(xi, hi + 0.012, f"{a:.3f}", ha="center", va="bottom",
                 fontsize=10, fontweight="bold",
                 bbox=dict(boxstyle="round,pad=0.12", fc="white", ec="none"))
        # White on the light NEUTRAL bar was unreadable; pick the label colour from
        # the bar it sits on rather than assuming every bar is dark.
        axR.text(xi, 0.408, f"n={n}", ha="center", va="bottom", fontsize=8.5,
                 color=fs.INK if c == fs.NEUTRAL else "white",
                 fontweight="bold", zorder=5)
    axR.axhline(0.5, color=fs.MUTED, linewidth=1.2, linestyle="--")
    axR.text(2.42, 0.5, "coin\nflip", va="center", ha="left", fontsize=8.5, color=fs.MUTED)
    axR.set_xticks(x)
    axR.set_xticklabels([b[0] for b in bars], fontsize=8.6)
    axR.set_ylabel("out-of-sample AUC  (P team scores > 4.5)")
    axR.set_ylim(0.40, 0.72)
    axR.set_xlim(-0.6, 2.9)
    axR.set_title("Debiasing collapses the signal toward a coin flip", fontsize=10.6, pad=8, wrap=True)
    fs.save_at_measure(fig, FIGDIR / "velocity_post_treatment_bias.png")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 5 — transfer function (market elasticity by event)
# ─────────────────────────────────────────────────────────────────────────────
def fig5_transfer():
    pa = _load("program_a.json")["by_type"]
    order = ["home_run", "triple", "double", "single", "hit_by_pitch", "walk"]
    nice = {"home_run": "HR", "triple": "3B", "double": "2B", "single": "1B",
            "hit_by_pitch": "HBP", "walk": "BB"}
    fs.setup()
    fig, ax = plt.subplots(figsize=(fs.FULL_W, 5.9))
    # per-event label offsets (points) chosen to avoid the fit line & each other
    off = {"home_run": (0, 16), "triple": (10, 6), "double": (10, 12),
           "single": (14, 2), "hit_by_pitch": (12, -4), "walk": (-12, -14)}
    ha_ = {"walk": "right"}
    xs, ys = [], []
    for i, ev in enumerate(order):
        d = pa[ev]
        x, y, n = d["avg_dre"], d["avg_book5"], d["n"]
        xs.append(x); ys.append(y)
        ax.scatter(x, y, s=40 + n / 6, color=fs.PALETTE[i % len(fs.PALETTE)],
                   edgecolor="white", linewidth=1.2, zorder=4)
        ax.annotate(f"{nice[ev]} (n={n})", (x, y), xytext=off[ev],
                    textcoords="offset points", fontsize=9, color=fs.INK,
                    va="center", ha=ha_.get(ev, "left"), bbox=HALO)

    lim = 1.6
    ax.plot([0, lim], [0, lim], color=fs.MUTED, linewidth=1.3, linestyle="--", zorder=2)
    ax.text(1.5, 1.55, "y = x\n(fully priced)", fontsize=8.5, color=fs.MUTED,
            ha="right", va="top", bbox=HALO)

    # one common slope through the origin over every event type (the key point:
    # the events don't scatter — they lie on a SINGLE line, so the sub-1 level is
    # uniform attenuation, not a per-event mispricing)
    xs_a, ys_a = np.array(xs), np.array(ys)
    slope = float(np.sum(xs_a * ys_a) / np.sum(xs_a * xs_a))
    ax.plot([0, lim], [0, slope * lim], color=fs.PALETTE[0], linewidth=2, zorder=3)
    ax.text(0.14, slope * 0.14 - 0.055, f"one common slope ≈ {slope:.2f}", fontsize=10.5,
            color=fs.PALETTE[0], ha="left", va="top", fontweight="bold", rotation=25,
            rotation_mode="anchor")

    ax.set_xlim(0, lim); ax.set_ylim(0, lim)
    ax.set_aspect("equal")
    ax.set_xlabel("true information shock  ΔRE  (runs, RE24-based)")
    ax.set_ylabel("converged line move  ΔBook (+5 min)")
    ax.set_title("Every event type lies on one common slope\n"
                 "uniform attenuation (a measurement low-pass filter), not a per-event edge",
                 fontsize=11, wrap=True)
    fs.save_at_measure(fig, FIGDIR / "transfer_function.png")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 6 — market calibration: implied vs realized remaining runs
# ─────────────────────────────────────────────────────────────────────────────
def fig6_calibration():
    # RIGHTS: this figure formerly read output/encompass_cache.json, which carries the
    # sharp-book line B per half-inning snapshot -- a verbatim third-party quoted value.
    # That cache is retained privately and is NOT redistributed. The figure is driven
    # instead by a pre-computed aggregate containing only binned means, confidence
    # intervals and histogram counts. There is deliberately NO fallback to the cache:
    # if the aggregate is missing this raises, rather than silently reaching for
    # restricted data.
    agg = json.loads((HERE / "figdata" / "fig_market_calibration_agg.json").read_text())
    rr = _load("remaining_runs.json")

    fs.setup()
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(fs.FULL_W, 3.7),
                                   gridspec_kw={"width_ratios": [1, 1]})

    # left — reliability deciles, read straight from the aggregate
    bins = agg["reliability_bins"]
    bx = np.array([b["mean_B"] for b in bins]); by = np.array([b["mean_Y"] for b in bins])
    blo = [b["ci_lo"] for b in bins]; bhi = [b["ci_hi"] for b in bins]
    lim = max(bx.max(), by.max()) * 1.05
    axL.plot([0, lim], [0, lim], color=fs.MUTED, linestyle="--", linewidth=1.2, zorder=1)
    axL.fill_between(bx, blo, bhi, color=fs.PALETTE[0], alpha=0.18, zorder=2)
    axL.plot(bx, by, "-o", color=fs.PALETTE[0], markersize=6, linewidth=2,
             markeredgecolor="white", zorder=3)
    axL.set_xlim(0, lim); axL.set_ylim(0, lim)
    axL.set_aspect("equal")
    axL.set_xlabel("market-implied remaining runs")
    axL.set_ylabel("realized remaining runs")
    axL.set_title("Market forecast ≈ calibrated (within this sample)", fontsize=11, wrap=True)
    axL.text(0.04 * lim, 0.92 * lim, "on the diagonal ⇒ approximately\ncalibrated in this sample",
             fontsize=8.5, color=fs.MUTED, bbox=HALO)

    # right — book-error (Y − B) distribution; the thing nothing predicts
    # Same 40 bins the histogram always had, now supplied as edges+counts rather than
    # recomputed from per-observation errors. Drawn with bar(align="edge") so the bars
    # land on identical coordinates.
    edges = np.array(agg["error_hist"]["bin_edges"], float)
    counts = np.array(agg["error_hist"]["counts"], float)
    err_mean = agg["error_mean"]
    axR.bar(edges[:-1], counts, width=np.diff(edges), align="edge",
            color=fs.PALETTE[4], edgecolor="white", linewidth=0.4, zorder=3)
    axR.axvline(0, color=fs.MUTED, linewidth=1.2, linestyle="--")
    axR.axvline(err_mean, color=fs.PALETTE[3], linewidth=2, zorder=4)
    axR.text(err_mean, axR.get_ylim()[1] * 0.96, f"  mean {err_mean:+.2f}",
             color=fs.PALETTE[3], fontsize=9.5, fontweight="bold", va="top", bbox=HALO)
    axR.set_xlabel("book forecast error  (realized − implied)")
    axR.set_ylabel("half-inning snapshots")
    axR.set_title("Error: right-skewed (mean +0.49, median 0); unpredictable (OOS R² ≈ 0)",
                  fontsize=9.5, wrap=True)
    fig.suptitle(f"Remaining-runs calibration · {rr['n']:,} snapshots · model R² = {rr['r2_base']:.3f}",
                 fontsize=12.5, fontweight="bold", wrap=True)
    fs.save_at_measure(fig, FIGDIR / "market_calibration.png")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 7 — the incremental-information funnel
# ─────────────────────────────────────────────────────────────────────────────
def fig7_funnel(matrix):
    # derive counts from the graveyard matrix so the funnel stays consistent.
    # matrix columns: [initial, robustness, out-of-sample, market-test, verdict];
    # a hypothesis holds "P" for every gate it CLEARED before the gate that killed it.
    P = "P"
    total = len(matrix)
    initial = sum(1 for _, c in matrix if c[0] == P)     # showed an in-sample signal
    oos = sum(1 for _, c in matrix if c[2] == P)          # cleared the out-of-sample gate
    beyond = sum(1 for _, c in matrix if c[3] == P)       # cleared the market test
    prof = sum(1 for _, c in matrix if c[4] == P)         # cleared the verdict (none)
    stages = [
        ("Hypotheses tested", total, fs.PALETTE[0]),
        ("Predict runs in-sample", initial, fs.PALETTE[0]),
        ("Survive out-of-sample", oos, fs.PALETTE[1]),
        ("Add info beyond the market", beyond, fs.PALETTE[3]),
        ("Exploitably profitable", prof, fs.FAIL),
    ]
    fs.setup()
    fig, ax = plt.subplots(figsize=(fs.FULL_W, 4.1))
    n = len(stages)
    for i, (lab, cnt, col) in enumerate(stages):
        y = n - 1 - i
        w = cnt / total
        if cnt > 0:
            ax.add_patch(plt.Rectangle((0, y + 0.14), w, 0.72, facecolor=col,
                                       edgecolor="white", linewidth=1.5, zorder=3))
        # stage label always in ink to the left margin (visible for empty bars too)
        ax.text(-0.015, y + 0.5, lab, ha="right", va="center", fontsize=10.5,
                color=fs.INK, zorder=4)
        end = w + 0.012 if cnt > 0 else 0.012
        ax.text(end, y + 0.5, str(cnt), ha="left", va="center", fontsize=13,
                fontweight="bold", color=col if cnt > 0 else fs.FAIL, zorder=4)
    ax.set_xlim(-0.62, 1.08)
    ax.set_ylim(0, n)
    ax.axis("off")
    ax.set_title("The incremental-information funnel\n"
                 "predicting runs is easy; predicting the market's error is the wall",
                 fontsize=12.5, fontweight="bold", loc="center", wrap=True)
    fs.save_at_measure(fig, FIGDIR / "incremental_information_funnel.png")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 1 — the research process (escalating tests and their outcomes)
# ─────────────────────────────────────────────────────────────────────────────
def fig1_process():
    # (stage, outcome, killed?)  — the study's actual course through the protocol
    steps = [
        ("Initial hypothesis:\ntimes-through-order penalty",
         "naive backtest: at or below breakeven", True),
        ("Velocity-decline signal",
         "debiasing: AUC 0.61 to 0.52 (selection)", True),
        ("Bullpen-fatigue multiplier",
         "no effect: fatigued pens concede no more", True),
        ("Remaining-runs model\n+ fatigue terms",
         "MAE unchanged; game state already suffices", True),
        ("Forecast encompassing\n(joint + per-feature)",
         "book error unpredictable, OOS R² near 0", True),
        ("Transfer function\n(ΔBook vs ΔRE)",
         "one common slope near 0.74, priced about right", False),
        ("Boundary identified",
         "open frontier: live market microstructure", False),
    ]
    fs.setup()
    fig, ax = plt.subplots(figsize=(fs.FULL_W, 4.9))
    n = len(steps)
    for i, (stage, outcome, killed) in enumerate(steps):
        y = n - 1 - i
        last = i == n - 1
        face = fs.INK if last else fs.PALETTE[0]
        ax.add_patch(plt.Rectangle((0.0, y + 0.12), 0.46, 0.76, facecolor=face,
                                   edgecolor="white", linewidth=1.5, zorder=3))
        ax.text(0.23, y + 0.5, stage, ha="center", va="center", color="white",
                fontsize=8.6, fontweight="bold", zorder=4)
        mark = "✗" if killed else "→"
        mcol = fs.FAIL if killed else fs.PASS
        ax.text(0.49, y + 0.5, mark, ha="center", va="center", color=mcol,
                fontsize=12, fontweight="bold")
        ax.text(0.525, y + 0.5, outcome, ha="left", va="center", color=fs.MUTED,
                fontsize=8.8)
        if not last:
            ax.annotate("", xy=(0.23, y + 0.03), xytext=(0.23, y + 0.12),
                        arrowprops=dict(arrowstyle="-|>", color=fs.MUTED, linewidth=1.4))
    ax.set_xlim(-0.02, 1.04)
    ax.set_ylim(-0.05, n + 0.05)
    ax.axis("off")
    # No auto-wrap here. matplotlib decides `wrap=True` breaks from the canvas width
    # at draw time, and this title sits within a few pixels of the measure, so the
    # raster and vector renditions of the same figure disagreed about it -- the PNG
    # broke a one-word widow onto a second line, the SVG did not. Setting the line
    # explicitly makes both renditions identical by construction. Same words, same
    # size, one line.
    # 11pt, the same size the other axes titles in this paper are set at. At 11.5 the
    # single line was the widest artist on the canvas, so it set the crop -- and the
    # raster and vector renderers disagree about a long string's width by about a
    # percent, which is enough to pull the two renditions out of register. At 11 the
    # crop is set by the figure body instead and both land on the measure.
    ax.set_title("The research process: each surviving explanation handed to a stricter test",
                 fontsize=11, pad=12)
    fs.save_at_measure(fig, FIGDIR / "research_process.png")
    plt.close(fig)


def fig_power():
    """Appendix B: every feature's incremental out-of-sample R2 against the detection floor."""
    inc = _load("encompass.json")["incremental"]
    mde = _load("revision1.json")["power"]
    nice = {"vdrop": "velocity decline", "back": "back-tier starter", "mid": "mid-tier starter",
            "pen": "bullpen quality", "tto": "times through order", "pc": "pitch count",
            "temp": "temperature", "wind": "wind", "park": "park", "inning": "inning"}
    items = sorted(inc.items(), key=lambda kv: kv[1])
    floor = mde["mde_r2_snap"]
    fs.setup()
    fig, ax = plt.subplots(figsize=(fs.FULL_W, 4.4))
    ys = np.arange(len(items))
    ax.axvspan(floor, 0.013, color=fs.PALETTE[2], alpha=0.06, zorder=0)
    for y, (k, v) in zip(ys, items):
        col = fs.NEUTRAL if abs(v) < 0.003 else (fs.PALETTE[0] if v > 0 else fs.PALETTE[3])
        ax.plot([0, v], [y, y], color=fs.GRID, lw=1.0, zorder=1)
        near0 = abs(v) < 0.003
        ax.plot([v], [y], marker="o", ms=8, color=col,
                markeredgecolor=fs.MUTED if near0 else "white",
                markeredgewidth=1.2 if near0 else 1.0, zorder=3)
    ax.axvline(0, color=fs.MUTED, lw=1.0)
    ax.axvline(floor, color=fs.INK, lw=1.4, ls="--")
    # The callout is wider than the shaded band it describes, so it necessarily
    # crosses the dashed floor rule. Set it in the standard annotation box so the
    # rule stops at the box edge instead of running through the glyphs.
    ax.text(0.985, 0.975,
            f"minimum detectable\nincremental R² = {floor:.3f}\n(80% power, snapshots independent)",
            transform=ax.transAxes, fontsize=8.5, color=fs.INK, va="top", ha="right",
            bbox=fs.box(fc="white"), zorder=5)
    ax.set_yticks(ys); ax.set_yticklabels([nice[k] for k, _ in items], fontsize=8.8)
    ax.set_xlabel("incremental out-of-sample R²  (beyond the market forecast)")
    ax.set_xlim(-0.009, 0.013); ax.set_ylim(-0.6, len(items) - 0.1)
    # Default locator put ~11 labels across the axis; six is legible at 8.5pt.
    ax.xaxis.set_major_locator(MaxNLocator(nbins=6))
    ax.set_title("Every feature's incremental information falls below the detection floor",
                 fontsize=11, pad=10, wrap=True)
    # Outside the plotting region entirely: at y=-0.75 in data coordinates this
    # note printed across the x-axis rule and its tick labels.
    ax.text(1.0, -0.155, f"conservative floor (games independent): {mde['mde_r2_games']:.2f}, off-scale right",
            transform=ax.transAxes, ha="right", va="top", fontsize=8.5,
            color=fs.MUTED, style="italic", clip_on=False)
    # No bottom-margin call here either: the note below the axis is clip_on=False,
    # so save_at_measure's tight bounding box already grows to include it.
    fs.save_at_measure(fig, FIGDIR / "appendix_power.png")
    plt.close(fig)


def main() -> int:
    fig1_process()
    rows = fig2_graveyard()
    fig3_encompassing()
    fig4_debiasing()
    fig5_transfer()
    fig6_calibration()
    fig7_funnel(rows)
    fig_power()
    made = sorted(p.name for p in FIGDIR.glob("*.png"))
    print("wrote:", ", ".join(made))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
