#!/usr/bin/env python3
"""Generate the paper's figure set (Fig 2–7) from committed result JSONs.

Figure 1 is the Mermaid research-process flow (in the outline). This script
produces the six data figures as PNGs in paper/figures/. Every number is read
from output/*.json (recomputable from the committed caches — no feed fetches).

    python the_third_turn/paper/make_figures.py

Figures are generated by filename; the manuscript figure NUMBERS are assigned by
order of appearance in paper1.md (which also includes the two conceptual figures
from make_concept_figures.py), so the numbering lives in the paper, not here.

Reviewer constraints honored throughout: uncertainty is shown (bootstrap /
Hanley-McNeil / Wilson CIs), near-zero differences are drawn NEUTRAL (the CI
does the arguing, not the color), typography is one coherent system (figstyle),
labels crossing gridlines wear a white halo, and the result is framed as a
BOUNDARY we identify — never a "negative result."
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Patch, FancyBboxPatch, FancyArrowPatch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import figstyle as fs  # noqa: E402

OUT = HERE.parent / "output"
FIGDIR = HERE / "figures"
FIGDIR.mkdir(exist_ok=True)

# white halo so a label crossing a gridline / mark stays legible
HALO = dict(facecolor="white", edgecolor="none", alpha=0.78, boxstyle="round,pad=0.15")


def _load(name):
    return json.loads((OUT / name).read_text())


def _wilson(k, n, z=1.96):
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (c - h, c + h)


def _hanley_mcneil_ci(a, n, prev, z=1.96):
    """Analytic 95% CI for an AUC (Hanley & McNeil 1982)."""
    n1 = max(int(round(prev * n)), 1)          # positives
    n2 = max(n - n1, 1)                          # negatives
    q1 = a / (2 - a)
    q2 = 2 * a * a / (1 + a)
    var = (a * (1 - a) + (n1 - 1) * (q1 - a * a) + (n2 - 1) * (q2 - a * a)) / (n1 * n2)
    se = math.sqrt(max(var, 0.0))
    return se, (max(a - z * se, 0.0), min(a + z * se, 1.0))


# ─────────────────────────────────────────────────────────────────────────────
# Figure 2 — the hypothesis graveyard
# ─────────────────────────────────────────────────────────────────────────────
def fig2_graveyard():
    stages = ["Initial\nsignal", "Robustness", "Out-of-\nsample", "Market\ntest", "Verdict"]
    P, F, N = "P", "F", "N"
    # each row: how far the hypothesis cleared before a gate killed it (Verdict always F)
    rows = [
        ("Times-through-order (TTOP)",      [P, F, N, N, F]),
        ("Velocity decline",               [P, F, N, N, F]),
        ("Bullpen-fatigue multiplier",     [F, N, N, N, F]),
        ("Drop reversion (Over)",          [P, P, F, N, F]),
        ("Drop reversion (Under)",         [P, F, N, N, F]),
        ("Alternate-line skew",            [P, P, P, F, F]),
        ("Early-run anchoring",            [P, P, P, F, F]),
        ("Weather / park context",         [P, P, P, F, F]),
        ("Remaining-runs fatigue term",    [P, F, N, N, F]),
        ("Forecast encompassing",          [P, P, F, F, F]),
    ]
    color = {P: fs.PASS, F: fs.FAIL, N: fs.GRID}
    glyph = {P: "✓", F: "✗", N: "·"}  # ✓ ✗ ·
    txtcol = {P: "white", F: "white", N: fs.MUTED}

    fs.setup()
    fig, ax = plt.subplots(figsize=(8.4, 5.0))
    nrows, ncols = len(rows), len(stages)
    for i, (_, cells) in enumerate(rows):
        y = nrows - 1 - i
        for j, c in enumerate(cells):
            ax.add_patch(plt.Rectangle((j + 0.06, y + 0.06), 0.88, 0.88,
                                       facecolor=color[c], edgecolor="white", linewidth=1.5))
            ax.text(j + 0.5, y + 0.5, glyph[c], ha="center", va="center",
                    color=txtcol[c], fontsize=13, fontweight="bold")
    ax.set_xlim(0, ncols)
    ax.set_ylim(0, nrows)
    ax.set_xticks([j + 0.5 for j in range(ncols)])
    ax.set_xticklabels(stages, fontsize=9)
    ax.set_yticks([nrows - 1 - i + 0.5 for i in range(nrows)])
    ax.set_yticklabels([r[0] for r in rows], fontsize=9)
    ax.xaxis.tick_top()
    ax.tick_params(length=0)
    for s in ax.spines.values():
        s.set_visible(False)
    ax.grid(False)
    ax.set_title("Each public-information candidate, tested against the market forecast",
                 pad=26, fontsize=12)
    legend = [Patch(facecolor=fs.PASS, label="cleared this test"),
              Patch(facecolor=fs.FAIL, label="failed here"),
              Patch(facecolor=fs.GRID, label="not reached")]
    ax.legend(handles=legend, loc="upper center", bbox_to_anchor=(0.5, -0.04),
              ncol=3, fontsize=9, handlelength=1.1)
    fig.savefig(FIGDIR / "hypothesis_elimination.png", bbox_inches="tight")
    plt.close(fig)
    return rows


# ─────────────────────────────────────────────────────────────────────────────
# Figure 3 — forecast encompassing
# ─────────────────────────────────────────────────────────────────────────────
def fig3_encompassing():
    e = _load("encompass.json")
    fs.setup()
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(9.2, 4.2),
                                   gridspec_kw={"width_ratios": [1, 1.25]})

    # left — three forecasts
    labels = ["Our features\n(Y ~ X)", "Sharp market\n(Y ~ B)", "Market + features\n(Y ~ B+X)"]
    vals = [e["r2_features"], e["r2_market"], e["r2_both"]]
    cols = [fs.PALETTE[1], fs.PALETTE[0], fs.PALETTE[2]]
    x = np.arange(3)
    axL.bar(x, vals, width=0.62, color=cols, zorder=3)
    for xi, v in zip(x, vals):
        axL.text(xi, v + 0.006, f"{v:.3f}", ha="center", va="bottom",
                 fontsize=10, fontweight="bold", color=fs.INK)
    # visual annotation over the combined bar — tells the reader what they're seeing
    axL.annotate("no incremental\ninformation", xy=(2, vals[2] + 0.004),
                 xytext=(2, vals[2] + 0.052), ha="center", va="bottom", fontsize=8.6,
                 color=fs.PALETTE[3], fontweight="bold",
                 arrowprops=dict(arrowstyle="-", color=fs.PALETTE[3], linewidth=1))
    axL.set_xticks(x)
    axL.set_xticklabels(labels, fontsize=9)
    axL.set_ylabel("out-of-sample R²  (remaining runs)")
    axL.set_ylim(0, max(vals) * 1.18)
    axL.set_title("Adding features to the market: ΔR² = %+.3f" % e["encompass_gain"],
                  fontsize=11, pad=10)

    # right — per-feature incremental ΔR² beyond the market (E+)
    inc = e["incremental"]
    order = sorted(inc.items(), key=lambda kv: kv[1])
    names = [k for k, _ in order]
    dvals = [v for _, v in order]
    y = np.arange(len(names))
    bar_cols = [fs.NEUTRAL if abs(v) < 0.003 else (fs.PALETTE[2] if v > 0 else fs.PALETTE[3])
                for v in dvals]
    axR.barh(y, dvals, color=bar_cols, zorder=3, height=0.66)
    axR.axvline(0, color=fs.MUTED, linewidth=1)
    axR.axvline(0.003, color=fs.GRID, linewidth=1, linestyle="--")
    axR.axvline(-0.003, color=fs.GRID, linewidth=1, linestyle="--")
    axR.set_yticks(y)
    axR.set_yticklabels(names, fontsize=9)
    axR.set_xlabel("incremental R² beyond the market  (Y~B+Xi − Y~B)")
    axR.set_title("Every feature, individually encompassed", fontsize=11)
    axR.text(0.0032, len(names) - 0.6, "±0.003\nnegligible band", fontsize=7.5,
             color=fs.MUTED, va="center")
    fig.suptitle("The sharp market statistically encompasses every public variable we measure",
                 fontsize=12.5, fontweight="bold")
    fig.savefig(FIGDIR / "forecast_encompassing.png", bbox_inches="tight")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 4 — velocity debiasing
# ─────────────────────────────────────────────────────────────────────────────
def fig4_debiasing():
    # recomputed from calibration.py (committed run): AUC / n / class prevalence
    prev = _load("calibration.json").get("base_rate", 0.429)
    bars = [
        ("BASELINE\ntier only, no velocity", 0.420, 272, fs.NEUTRAL),
        ("POST-TREATMENT\nvel drop 1st→3rd time", 0.610, 272, fs.PALETTE[3]),
        ("DEBIASED\nearly-window decline", 0.524, 319, fs.PALETTE[0]),
    ]
    fs.setup()
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(11.2, 5.0),
                                   gridspec_kw={"width_ratios": [0.95, 1.0]})

    # ---- LEFT: the survivorship flow (why the raw signal is post-treatment) ----
    axL.set_xlim(0, 10); axL.set_ylim(0, 10); axL.axis("off")

    def _fbox(x, y, w, h, fc, ec=None, lw=1.4):
        axL.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.02,rounding_size=0.12",
                                     facecolor=fc, edgecolor=ec or "white", linewidth=lw, zorder=3))

    def _farrow(x0, y0, x1, y1, color=None, lw=1.9):
        axL.add_patch(FancyArrowPatch((x0, y0), (x1, y1), arrowstyle="-|>", mutation_scale=13,
                                      color=color or fs.MUTED, linewidth=lw, zorder=2,
                                      shrinkA=0, shrinkB=0))

    _fbox(1.7, 8.35, 6.6, 1.25, fs.PALETTE[0])
    axL.text(5.0, 8.97, "100 starters take the mound", ha="center", va="center",
             color="white", fontsize=9.8, fontweight="bold")
    _farrow(4.1, 8.35, 2.4, 6.95)
    _farrow(5.9, 8.35, 7.6, 6.95, color=fs.PASS)
    _fbox(0.25, 5.5, 3.9, 1.45, "#ECECEC", ec=fs.GRID)
    axL.text(2.2, 6.42, "pulled or shelled early", ha="center", va="center", color=fs.MUTED,
             fontsize=8.4, fontweight="bold")
    axL.text(2.2, 6.02, "(before the 3rd time through)", ha="center", va="center",
             color=fs.MUTED, fontsize=7.5)
    axL.text(2.2, 5.05, "✗ leaves the sample", ha="center", va="center", color=fs.FAIL,
             fontsize=8.0, fontweight="bold")
    _fbox(5.75, 5.5, 4.0, 1.45, fs.PASS)
    axL.text(7.75, 6.42, "survive to face the", ha="center", va="center", color="white",
             fontsize=8.7, fontweight="bold")
    axL.text(7.75, 6.02, "order a 3rd time", ha="center", va="center", color="white",
             fontsize=8.7, fontweight="bold")
    _farrow(7.75, 5.5, 5.85, 3.8)
    _fbox(1.5, 2.2, 8.3, 1.5, fs.INK)
    axL.text(5.65, 3.17, "velocity decline measured HERE", ha="center", va="center",
             color="white", fontsize=9.0, fontweight="bold")
    axL.text(5.65, 2.68, "only on survivors, pitchers already good enough to last",
             ha="center", va="center", color="white", fontsize=7.7)
    axL.text(5.0, 1.15, "the sample is conditioned on survival,\nso the raw signal is post-treatment",
             ha="center", va="center", color=fs.MUTED, fontsize=8.2, style="italic")
    axL.set_title("A signal defined only on the survivors", fontsize=10.6, pad=8)

    # ---- RIGHT: the AUC drop under debiasing ----
    x = np.arange(len(bars))
    for xi, (lab, a, n, c) in zip(x, bars):
        se, (lo, hi) = _hanley_mcneil_ci(a, n, prev)
        axR.bar(xi, a, width=0.6, color=c, zorder=3)
        axR.errorbar(xi, a, yerr=[[a - lo], [hi - a]], fmt="none",
                     ecolor=fs.INK, elinewidth=1.4, capsize=5, zorder=4)
        axR.text(xi, hi + 0.006, f"{a:.3f}", ha="center", va="bottom",
                 fontsize=10, fontweight="bold")
        axR.text(xi, 0.408, f"n={n}", ha="center", va="bottom", fontsize=8.5,
                 color="white", fontweight="bold", zorder=5)
    axR.axhline(0.5, color=fs.MUTED, linewidth=1.2, linestyle="--")
    axR.text(2.42, 0.5, "coin\nflip", va="center", ha="left", fontsize=8.5, color=fs.MUTED)
    axR.set_xticks(x)
    axR.set_xticklabels([b[0] for b in bars], fontsize=8.6)
    axR.set_ylabel("out-of-sample AUC  (P team scores > 4.5)")
    axR.set_ylim(0.40, 0.72)
    axR.set_xlim(-0.6, 2.9)
    axR.set_title("Debiasing collapses the signal toward a coin flip", fontsize=10.6, pad=8)
    fig.savefig(FIGDIR / "velocity_post_treatment_bias.png", bbox_inches="tight")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 5 — transfer function (market elasticity by event)
# ─────────────────────────────────────────────────────────────────────────────
def fig5_transfer():
    pa = _load("program_a.json")["by_type"]
    order = ["home_run", "triple", "double", "single", "hit_by_pitch", "walk"]
    nice = {"home_run": "HR", "triple": "3B", "double": "2B", "single": "1B",
            "hit_by_pitch": "HBP", "walk": "BB"}
    fs.setup()
    fig, ax = plt.subplots(figsize=(7.2, 6.2))
    # per-event label offsets (points) chosen to avoid the fit line & each other
    off = {"home_run": (0, 16), "triple": (10, 6), "double": (10, 12),
           "single": (14, 2), "hit_by_pitch": (12, -4), "walk": (-12, -14)}
    ha_ = {"walk": "right"}
    xs, ys = [], []
    for i, ev in enumerate(order):
        d = pa[ev]
        x, y, n = d["avg_dre"], d["avg_book5"], d["n"]
        xs.append(x); ys.append(y)
        ax.scatter(x, y, s=40 + n / 6, color=fs.PALETTE[i % len(fs.PALETTE)],
                   edgecolor="white", linewidth=1.2, zorder=4)
        ax.annotate(f"{nice[ev]} (n={n})", (x, y), xytext=off[ev],
                    textcoords="offset points", fontsize=9, color=fs.INK,
                    va="center", ha=ha_.get(ev, "left"), bbox=HALO)

    lim = 1.6
    ax.plot([0, lim], [0, lim], color=fs.MUTED, linewidth=1.3, linestyle="--", zorder=2)
    ax.text(1.5, 1.55, "y = x\n(fully priced)", fontsize=8.5, color=fs.MUTED,
            ha="right", va="top", bbox=HALO)

    # one common slope through the origin over every event type (the key point:
    # the events don't scatter — they lie on a SINGLE line, so the sub-1 level is
    # uniform attenuation, not a per-event mispricing)
    xs_a, ys_a = np.array(xs), np.array(ys)
    slope = float(np.sum(xs_a * ys_a) / np.sum(xs_a * xs_a))
    ax.plot([0, lim], [0, slope * lim], color=fs.PALETTE[0], linewidth=2, zorder=3)
    ax.text(0.14, slope * 0.14 - 0.055, f"one common slope ≈ {slope:.2f}", fontsize=10.5,
            color=fs.PALETTE[0], ha="left", va="top", fontweight="bold", rotation=25,
            rotation_mode="anchor")

    ax.set_xlim(0, lim); ax.set_ylim(0, lim)
    ax.set_aspect("equal")
    ax.set_xlabel("true information shock  ΔRE  (runs, RE24-based)")
    ax.set_ylabel("converged line move  ΔBook (+5 min)")
    ax.set_title("Every event type lies on one common slope\n"
                 "uniform attenuation (a measurement low-pass filter), not a per-event edge",
                 fontsize=11)
    fig.savefig(FIGDIR / "transfer_function.png", bbox_inches="tight")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 6 — market calibration: implied vs realized remaining runs
# ─────────────────────────────────────────────────────────────────────────────
def fig6_calibration():
    cache = _load("encompass_cache.json")
    Y = np.array([r["Y"] for r in cache], float)   # realized remaining runs
    B = np.array([r["B"] for r in cache], float)   # market-implied remaining runs
    rr = _load("remaining_runs.json")

    fs.setup()
    fig, (axL, axR) = plt.subplots(1, 2, figsize=(9.4, 4.3),
                                   gridspec_kw={"width_ratios": [1, 1]})

    # left — reliability: bin by predicted B (deciles), plot mean realized Y ± Wilson-ish SE
    qs = np.quantile(B, np.linspace(0, 1, 11))
    qs[-1] += 1e-6
    idx = np.clip(np.digitize(B, qs) - 1, 0, 9)
    bx, by, blo, bhi = [], [], [], []
    for b in range(10):
        m = idx == b
        if m.sum() < 5:
            continue
        bx.append(B[m].mean()); by.append(Y[m].mean())
        se = Y[m].std(ddof=1) / math.sqrt(m.sum())
        blo.append(Y[m].mean() - 1.96 * se); bhi.append(Y[m].mean() + 1.96 * se)
    bx, by = np.array(bx), np.array(by)
    lim = max(bx.max(), by.max()) * 1.05
    axL.plot([0, lim], [0, lim], color=fs.MUTED, linestyle="--", linewidth=1.2, zorder=1)
    axL.fill_between(bx, blo, bhi, color=fs.PALETTE[0], alpha=0.18, zorder=2)
    axL.plot(bx, by, "-o", color=fs.PALETTE[0], markersize=6, linewidth=2,
             markeredgecolor="white", zorder=3)
    axL.set_xlim(0, lim); axL.set_ylim(0, lim)
    axL.set_aspect("equal")
    axL.set_xlabel("market-implied remaining runs")
    axL.set_ylabel("realized remaining runs")
    axL.set_title("Market forecast ≈ calibrated (within this sample)", fontsize=11)
    axL.text(0.04 * lim, 0.92 * lim, "on the diagonal ⇒ approximately\ncalibrated in this sample",
             fontsize=8.5, color=fs.MUTED, bbox=HALO)

    # right — book-error (Y − B) distribution; the thing nothing predicts
    err = Y - B
    axR.hist(err, bins=40, color=fs.PALETTE[4], edgecolor="white", linewidth=0.4, zorder=3)
    axR.axvline(0, color=fs.MUTED, linewidth=1.2, linestyle="--")
    axR.axvline(err.mean(), color=fs.PALETTE[3], linewidth=2, zorder=4)
    axR.text(err.mean(), axR.get_ylim()[1] * 0.96, f"  mean {err.mean():+.2f}",
             color=fs.PALETTE[3], fontsize=9.5, fontweight="bold", va="top", bbox=HALO)
    axR.set_xlabel("book forecast error  (realized − implied)")
    axR.set_ylabel("half-inning snapshots")
    axR.set_title("Error: right-skewed (mean +0.49, median 0); unpredictable (OOS R² ≈ 0)",
                  fontsize=9.5)
    fig.suptitle(f"Remaining-runs calibration · {rr['n']:,} snapshots · model R² = {rr['r2_base']:.3f}",
                 fontsize=12.5, fontweight="bold")
    fig.savefig(FIGDIR / "market_calibration.png", bbox_inches="tight")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 7 — the incremental-information funnel
# ─────────────────────────────────────────────────────────────────────────────
def fig7_funnel(matrix):
    # derive counts from the graveyard matrix so the funnel stays consistent.
    # matrix columns: [initial, robustness, out-of-sample, market-test, verdict];
    # a hypothesis holds "P" for every gate it CLEARED before the gate that killed it.
    P = "P"
    total = len(matrix)
    initial = sum(1 for _, c in matrix if c[0] == P)     # showed an in-sample signal
    oos = sum(1 for _, c in matrix if c[2] == P)          # cleared the out-of-sample gate
    beyond = sum(1 for _, c in matrix if c[3] == P)       # cleared the market test
    prof = sum(1 for _, c in matrix if c[4] == P)         # cleared the verdict (none)
    stages = [
        ("Hypotheses tested", total, fs.PALETTE[0]),
        ("Predict runs in-sample", initial, fs.PALETTE[0]),
        ("Survive out-of-sample", oos, fs.PALETTE[1]),
        ("Add info beyond the market", beyond, fs.PALETTE[3]),
        ("Exploitably profitable", prof, fs.FAIL),
    ]
    fs.setup()
    fig, ax = plt.subplots(figsize=(8.6, 4.8))
    n = len(stages)
    for i, (lab, cnt, col) in enumerate(stages):
        y = n - 1 - i
        w = cnt / total
        if cnt > 0:
            ax.add_patch(plt.Rectangle((0, y + 0.14), w, 0.72, facecolor=col,
                                       edgecolor="white", linewidth=1.5, zorder=3))
        # stage label always in ink to the left margin (visible for empty bars too)
        ax.text(-0.015, y + 0.5, lab, ha="right", va="center", fontsize=10.5,
                color=fs.INK, zorder=4)
        end = w + 0.012 if cnt > 0 else 0.012
        ax.text(end, y + 0.5, str(cnt), ha="left", va="center", fontsize=13,
                fontweight="bold", color=col if cnt > 0 else fs.FAIL, zorder=4)
    ax.set_xlim(-0.62, 1.08)
    ax.set_ylim(0, n)
    ax.axis("off")
    ax.set_title("The incremental-information funnel\n"
                 "predicting runs is easy; predicting the market's error is the wall",
                 fontsize=12.5, fontweight="bold", loc="center")
    fig.savefig(FIGDIR / "incremental_information_funnel.png", bbox_inches="tight")
    plt.close(fig)


# ─────────────────────────────────────────────────────────────────────────────
# Figure 1 — the research process (escalating tests and their outcomes)
# ─────────────────────────────────────────────────────────────────────────────
def fig1_process():
    # (stage, outcome, killed?)  — the study's actual course through the protocol
    steps = [
        ("Initial hypothesis:\ntimes-through-order penalty",
         "naive backtest: at or below breakeven", True),
        ("Velocity-decline signal",
         "debiasing: AUC 0.61 to 0.52 (selection)", True),
        ("Bullpen-fatigue multiplier",
         "no effect: fatigued pens concede no more", True),
        ("Remaining-runs model\n+ fatigue terms",
         "MAE unchanged; game state already suffices", True),
        ("Forecast encompassing\n(joint + per-feature)",
         "book error unpredictable, OOS R² near 0", True),
        ("Transfer function\n(ΔBook vs ΔRE)",
         "one common slope near 0.74, priced about right", False),
        ("Boundary identified",
         "open frontier: live market microstructure", False),
    ]
    fs.setup()
    fig, ax = plt.subplots(figsize=(8.6, 5.8))
    n = len(steps)
    for i, (stage, outcome, killed) in enumerate(steps):
        y = n - 1 - i
        last = i == n - 1
        face = fs.INK if last else fs.PALETTE[0]
        ax.add_patch(plt.Rectangle((0.0, y + 0.12), 0.46, 0.76, facecolor=face,
                                   edgecolor="white", linewidth=1.5, zorder=3))
        ax.text(0.23, y + 0.5, stage, ha="center", va="center", color="white",
                fontsize=8.6, fontweight="bold", zorder=4)
        mark = "✗" if killed else "→"
        mcol = fs.FAIL if killed else fs.PASS
        ax.text(0.49, y + 0.5, mark, ha="center", va="center", color=mcol,
                fontsize=12, fontweight="bold")
        ax.text(0.525, y + 0.5, outcome, ha="left", va="center", color=fs.MUTED,
                fontsize=8.8)
        if not last:
            ax.annotate("", xy=(0.23, y + 0.03), xytext=(0.23, y + 0.12),
                        arrowprops=dict(arrowstyle="-|>", color=fs.MUTED, linewidth=1.4))
    ax.set_xlim(-0.02, 1.04)
    ax.set_ylim(-0.05, n + 0.05)
    ax.axis("off")
    ax.set_title("The research process: each surviving explanation handed to a stricter test",
                 fontsize=11.5, pad=12)
    fig.savefig(FIGDIR / "research_process.png", bbox_inches="tight")
    plt.close(fig)


def fig_power():
    """Appendix B: every feature's incremental out-of-sample R2 against the detection floor."""
    inc = _load("encompass.json")["incremental"]
    mde = _load("revision1.json")["power"]
    nice = {"vdrop": "velocity decline", "back": "back-tier starter", "mid": "mid-tier starter",
            "pen": "bullpen quality", "tto": "times through order", "pc": "pitch count",
            "temp": "temperature", "wind": "wind", "park": "park", "inning": "inning"}
    items = sorted(inc.items(), key=lambda kv: kv[1])
    floor = mde["mde_r2_snap"]
    fs.setup()
    fig, ax = plt.subplots(figsize=(7.8, 4.8))
    ys = np.arange(len(items))
    ax.axvspan(floor, 0.013, color=fs.PALETTE[2], alpha=0.06, zorder=0)
    for y, (k, v) in zip(ys, items):
        col = fs.NEUTRAL if abs(v) < 0.003 else (fs.PALETTE[0] if v > 0 else fs.PALETTE[3])
        ax.plot([0, v], [y, y], color=fs.GRID, lw=1.0, zorder=1)
        ax.plot([v], [y], marker="o", ms=8, color=col, markeredgecolor="white",
                markeredgewidth=1.0, zorder=3)
    ax.axvline(0, color=fs.MUTED, lw=1.0)
    ax.axvline(floor, color=fs.INK, lw=1.4, ls="--")
    ax.text(floor + 0.0003, len(items) - 0.4,
            f"minimum detectable\nincremental R² = {floor:.3f}\n(80% power, snapshots independent)",
            fontsize=7.8, color=fs.INK, va="top", ha="left")
    ax.set_yticks(ys); ax.set_yticklabels([nice[k] for k, _ in items], fontsize=8.8)
    ax.set_xlabel("incremental out-of-sample R²  (beyond the market forecast)")
    ax.set_xlim(-0.009, 0.013); ax.set_ylim(-0.9, len(items) - 0.1)
    ax.set_title("Every feature's incremental information falls below the detection floor",
                 fontsize=11, pad=10)
    ax.text(0.013, -0.75, f"conservative floor (games independent): {mde['mde_r2_games']:.2f}, off-scale right",
            ha="right", va="center", fontsize=7.6, color=fs.MUTED, style="italic")
    fig.savefig(FIGDIR / "appendix_power.png", bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    fig1_process()
    rows = fig2_graveyard()
    fig3_encompassing()
    fig4_debiasing()
    fig5_transfer()
    fig6_calibration()
    fig7_funnel(rows)
    fig_power()
    made = sorted(p.name for p in FIGDIR.glob("*.png"))
    print("wrote:", ", ".join(made))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
