#!/usr/bin/env python3
"""Generate anonymized submission variants of the manuscripts.

Every venue on the shortlist (Management Science, IJF, JBES, JFEC, JSE, IMC, PAM)
reviews double-anonymized. The working-paper manuscripts carry an author block, an
affiliation, an email, and a repository URL, all of which must come out.

    python3 the_third_turn/paper/make_anonymous.py
    python3 the_third_turn/paper/build_pdf.py paper1_anon
    python3 the_third_turn/paper/build_pdf.py paper2_anon

WHAT IS DELIBERATELY NOT REMOVED. The method names -- "Third Turn Protocol",
"Third Turn Benchmark Dataset" -- stay. Naming your own method is standard in
anonymized submission and removing it would make the contribution unreadable.
It does leave a residual de-anonymization path, because the protocol is public
under the author's name. Disclose the public working paper in the cover letter;
at IMC that residual is what the "unique capabilities" exception exists for.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
WITHHELD = "`[repository URL withheld for anonymous review]`"

# (pattern, replacement) applied in order. Substrings, not regexes, unless noted.
LITERAL = [
    ('<p class="author">Alec Messino<br/><span class="affil">The Third Turn Research '
     'Initiative &middot; alec.messino@gmail.com</span></p>',
     '<p class="author">[Author names withheld for anonymous review]</p>'),
    # Journal-submission copies drop the working-paper solicitation; paper1.md keeps it.
    ('<p class="wp">Working Paper &middot; July 2026 &middot; Comments welcome</p>',
     '<p class="wp">Working Paper &middot; July 2026</p>'),
    ("`https://github.com/alecmessino/third-turn`", WITHHELD),
    ("https://github.com/alecmessino/third-turn", "[repository URL withheld for anonymous review]"),
    ("alec.messino@gmail.com", "[email withheld]"),
    ("The Third Turn Research Initiative", "[affiliation withheld]"),
    # Paper 1's companion-study citation and its reference entry.
    ("(Messino 2026)", "(Author 2026)"),
    ('Messino, A. (2026). "What Prices Cannot Tell You: Identification Limits of Information\nTransmission in High-Frequency Markets." Working paper, [affiliation withheld].',
     'Author (2026). "What Prices Cannot Tell You: Identification Limits of Information\nTransmission in High-Frequency Markets." Working paper. [Reference anonymized for review.]'),
]


def anonymize(text: str) -> str:
    for old, new in LITERAL:
        text = text.replace(old, new)
    # Any surviving self-reference in the citation style used by this manuscript.
    text = re.sub(r"\bMessino,?\s+(?:A\.\s*)?\(2026\)", "Author (2026)", text)
    return text


def main() -> int:
    failures = []
    for stem in ("paper1", "paper2", "paper2_journal", "paper2_supplement"):
        src = HERE / f"{stem}.md"
        out = HERE / f"{stem}_anon.md"
        text = anonymize(src.read_text())
        banner = (
            "<!-- ANONYMIZED SUBMISSION COPY. Generated by paper/make_anonymous.py from "
            f"{stem}.md; do not edit by hand. The manuscript of record is {stem}.md. -->\n"
        )
        out.write_text(banner + text)
        # Verify: no identifying token may survive.
        leaks = [t for t in ("Messino", "alec.messino", "github.com/alecmessino",
                             "Third Turn Research Initiative") if t in text]
        print(f"{out.name}: {'OK' if not leaks else 'LEAKS ' + ', '.join(leaks)}")
        if leaks:
            failures.append(out.name)
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
